### ISSUE TITLE
Enhance the CSRF tokens

### ISSUE THREAD

**Issue by camfindlay** [data-govt-nz/ckanext-security#25]
Look to amend our tokens using the approach put forward at https://github.com/qld-gov-au/ckan-ex-qgov/pull/6/files

**Comment by ThrawnCA** [comment]
Description is at https://github.com/data-govt-nz/ckanext-security/issues/23#issuecomment-508620040

**Comment by ThrawnCA** [comment]
Bump.

We've been running data.qld.gov.au and publications.qld.gov.au on the new HMAC-based token format for several months, and it seems to be working well.

**Comment by camfindlay** [comment]
@ThrawnCA nice one! Take it we can close this issue?

**Comment by ThrawnCA** [comment]
@camfindlay No, what I'm suggesting is that the HMAC-based token format from https://github.com/qld-gov-au/ckan-ex-qgov/pull/6/ should be merged into this extension. It can't just be cherry-picked, because things were restructured a bit when importing our CSRF filter into ckanext-security, but it should be pretty straightforward.
